import test from 'node:test';
import assert from 'node:assert/strict';
import {validateAssetSet,spriteAttr,spriteExt,cellAttr,encodePalette,encodePaletteConfig,encodeTileset,chrBankAddress} from '../packages/assets/dist/index.js';
import {validateProjectManifest,fromStudioProjectV2,toStudioProjectV2} from '../packages/project/dist/index.js';

const tileset=(id='tileset:gfx',name='Graphics')=>({format:'clementina-tileset',version:1,id,name,bpp:3,chr:Array(6144).fill(0),authoring:{tilePaletteBanks:Array(256).fill(0),compositions:[]}});
const shape=(id='shape:hero',tilesetId='tileset:gfx')=>({format:'clementina-shape',version:1,id,name:'Hero',tilesetId,sprites:[{tile:1,x:-8,y:16,paletteBank:3,flipX:true,flipY:false}]});
const assetSet=()=>({palettes:[{format:'clementina-palette',version:1,id:'palette:p',name:'P',colors:Array(8).fill(0)}],paletteConfigs:[{format:'clementina-palette-config',version:1,id:'palette-config:c',name:'C',banks:['palette:p',...Array(15).fill(null)]}],tilesets:[tileset()],shapes:[shape()],animations:[{format:'clementina-animation',version:1,id:'animation:walk',name:'Walk',frames:[{shapeId:'shape:hero',ticks:6}]}]});

test('portable asset set validates',()=>validateAssetSet(assetSet()));
test('animation cannot cross sprite tilesets',()=>{const a=assetSet();a.tilesets.push(tileset('tileset:other','Other'));a.shapes.push({...shape('shape:other','tileset:other'),name:'Other'});a.animations[0].frames.push({shapeId:'shape:other',ticks:6});assert.throws(()=>validateAssetSet(a),/same tileset/)});
test('hardware attribute encoders retain Studio bit layouts',()=>{assert.equal(spriteAttr({paletteBank:5,flipX:true,flipY:true}),0x65);assert.equal(spriteExt({x:-512,y:-256}),0x06);assert.equal(cellAttr({paletteBank:0,flipX:true,flipY:true,priority:true,chrAlt:true}),0xf0)});
test('portable palette and CHR assets emit exact MIA byte layouts',()=>{const a=assetSet();a.palettes[0].colors=[0x0000,0x1234,0xabcd,0xffff,1,2,3,4];const bank=encodePalette(a.palettes[0]);assert.deepEqual(Array.from(bank.slice(0,8)),[0,0,0x34,0x12,0xcd,0xab,0xff,0xff]);const memory=encodePaletteConfig(a.paletteConfigs[0],a.palettes);assert.equal(memory.length,256);assert.deepEqual(memory.slice(0,16),bank);assert.deepEqual(memory.slice(16),new Uint8Array(240));a.tilesets[0].chr[1]=255;const chr=encodeTileset(a.tilesets[0]);assert.equal(chr.length,6144);assert.equal(chr[1],255);assert.equal(chrBankAddress(0),0x200);assert.equal(chrBankAddress(7),0xaa00);assert.throws(()=>chrBankAddress(8),/0 through 7/)});
test('project manifest rejects paths escaping root',()=>{const m={format:'clementina-project',version:1,name:'X',target:{machine:'clementina-6502',phi2Hz:1200000},program:{kind:'basic',entry:'src/main.bas'},assets:{palettes:[],paletteConfigs:[],tilesets:[],shapes:[],animations:[]}};validateProjectManifest(m);assert.throws(()=>validateProjectManifest({...m,program:{...m.program,entry:'../main.bas'}}))});
test('Studio v2 conversion excludes session-only state and round-trips reusable content',()=>{const s={paletteLibrary:[{id:'palette:p',name:'P',colors:Array(8).fill(0)}],paletteConfigs:[{id:'palette-config:c',name:'C',banks:['palette:p',...Array(15).fill(null)]}],activeConfigId:'palette-config:c',tilesets:[{id:'tileset:gfx',name:'Graphics',bpp:3,chr:Array(6144).fill(0),previewBackground:'#123456',tilePaletteBanks:Array(256).fill(0),compositions:[]}],shapes:[{id:'shape:hero',name:'Hero',tilesetId:'tileset:gfx',sprites:[{tile:1,x:0,y:0,paletteBank:0,flipX:false,flipY:false}]}],animations:[{name:'Idle',frames:[{shapeId:'shape:hero',ticks:8}]}]};const p=fromStudioProjectV2(s);assert.equal('previewBackground' in p.tilesets[0],false);const back=toStudioProjectV2(p);assert.equal(back.shapes[0].id,'shape:hero');assert.equal(back.animations[0].frames[0].shapeId,'shape:hero')});
