// Generated by scripts/generate-schemas.mjs. Do not edit.
export const schemas = {
  "palette": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://clementina.dev/schema/palette.schema.json",
    "title": "Clementina palette",
    "type": "object",
    "additionalProperties": false,
    "required": [
      "format",
      "version",
      "id",
      "name",
      "colors"
    ],
    "properties": {
      "format": {
        "const": "clementina-palette"
      },
      "version": {
        "const": 1
      },
      "id": {
        "type": "string",
        "pattern": "^[A-Za-z0-9][A-Za-z0-9._:-]{0,63}$"
      },
      "name": {
        "type": "string",
        "minLength": 1,
        "maxLength": 64
      },
      "colors": {
        "type": "array",
        "minItems": 8,
        "maxItems": 8,
        "items": {
          "type": "integer",
          "minimum": 0,
          "maximum": 65535
        }
      }
    }
  },
  "palette-config": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://clementina.dev/schema/palette-config.schema.json",
    "title": "Clementina palette-bank configuration",
    "type": "object",
    "additionalProperties": false,
    "required": [
      "format",
      "version",
      "id",
      "name",
      "banks"
    ],
    "properties": {
      "format": {
        "const": "clementina-palette-config"
      },
      "version": {
        "const": 1
      },
      "id": {
        "type": "string",
        "pattern": "^[A-Za-z0-9][A-Za-z0-9._:-]{0,63}$"
      },
      "name": {
        "type": "string",
        "minLength": 1,
        "maxLength": 64
      },
      "banks": {
        "type": "array",
        "minItems": 16,
        "maxItems": 16,
        "items": {
          "anyOf": [
            {
              "type": "string",
              "pattern": "^[A-Za-z0-9][A-Za-z0-9._:-]{0,63}$"
            },
            {
              "type": "null"
            }
          ]
        }
      }
    }
  },
  "tileset": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://clementina.dev/schema/tileset.schema.json",
    "title": "Clementina tileset",
    "type": "object",
    "additionalProperties": false,
    "required": [
      "format",
      "version",
      "id",
      "name",
      "bpp",
      "chr",
      "authoring"
    ],
    "properties": {
      "format": {
        "const": "clementina-tileset"
      },
      "version": {
        "const": 1
      },
      "id": {
        "type": "string",
        "pattern": "^[A-Za-z0-9][A-Za-z0-9._:-]{0,63}$"
      },
      "name": {
        "type": "string",
        "pattern": "^[A-Za-z][A-Za-z0-9_-]{0,47}$"
      },
      "bpp": {
        "enum": [
          1,
          3
        ]
      },
      "chr": {
        "type": "array",
        "minItems": 6144,
        "maxItems": 6144,
        "items": {
          "type": "integer",
          "minimum": 0,
          "maximum": 255
        }
      },
      "authoring": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "tilePaletteBanks",
          "compositions"
        ],
        "properties": {
          "tilePaletteBanks": {
            "type": "array",
            "minItems": 256,
            "maxItems": 256,
            "items": {
              "type": "integer",
              "minimum": 0,
              "maximum": 15
            }
          },
          "compositions": {
            "type": "array",
            "items": {
              "type": "object",
              "additionalProperties": false,
              "required": [
                "name",
                "x",
                "y",
                "width",
                "height"
              ],
              "properties": {
                "name": {
                  "type": "string",
                  "minLength": 1,
                  "maxLength": 64
                },
                "x": {
                  "type": "integer",
                  "minimum": 0,
                  "maximum": 15
                },
                "y": {
                  "type": "integer",
                  "minimum": 0,
                  "maximum": 15
                },
                "width": {
                  "type": "integer",
                  "minimum": 1,
                  "maximum": 16
                },
                "height": {
                  "type": "integer",
                  "minimum": 1,
                  "maximum": 16
                }
              }
            }
          }
        }
      }
    }
  },
  "shape": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://clementina.dev/schema/shape.schema.json",
    "title": "Clementina shape",
    "type": "object",
    "additionalProperties": false,
    "required": [
      "format",
      "version",
      "id",
      "name",
      "tilesetId",
      "sprites"
    ],
    "properties": {
      "format": {
        "const": "clementina-shape"
      },
      "version": {
        "const": 1
      },
      "id": {
        "type": "string",
        "pattern": "^[A-Za-z0-9][A-Za-z0-9._:-]{0,63}$"
      },
      "name": {
        "type": "string",
        "pattern": "^[A-Za-z][A-Za-z0-9_]{0,31}$"
      },
      "tilesetId": {
        "type": "string",
        "pattern": "^[A-Za-z0-9][A-Za-z0-9._:-]{0,63}$"
      },
      "canvasPixelWidth": {
        "type": "integer",
        "minimum": 1,
        "maximum": 320
      },
      "canvasPixelHeight": {
        "type": "integer",
        "minimum": 1,
        "maximum": 200
      },
      "originAnchor": {
        "enum": [
          "top-left",
          "center",
          "bottom-center",
          "custom"
        ]
      },
      "originX": {
        "type": "integer",
        "minimum": -32768,
        "maximum": 32767
      },
      "originY": {
        "type": "integer",
        "minimum": -32768,
        "maximum": 32767
      },
      "sprites": {
        "type": "array",
        "maxItems": 64,
        "items": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "tile",
            "x",
            "y",
            "paletteBank",
            "flipX",
            "flipY"
          ],
          "properties": {
            "tile": {
              "type": "integer",
              "minimum": 0,
              "maximum": 255
            },
            "x": {
              "type": "integer",
              "minimum": -512,
              "maximum": 511
            },
            "y": {
              "type": "integer",
              "minimum": -256,
              "maximum": 255
            },
            "paletteBank": {
              "type": "integer",
              "minimum": 0,
              "maximum": 15
            },
            "flipX": {
              "type": "boolean"
            },
            "flipY": {
              "type": "boolean"
            }
          }
        }
      }
    }
  },
  "animation": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://clementina.dev/schema/animation.schema.json",
    "title": "Clementina animation",
    "type": "object",
    "additionalProperties": false,
    "required": [
      "format",
      "version",
      "id",
      "name",
      "frames"
    ],
    "properties": {
      "format": {
        "const": "clementina-animation"
      },
      "version": {
        "const": 1
      },
      "id": {
        "type": "string",
        "pattern": "^[A-Za-z0-9][A-Za-z0-9._:-]{0,63}$"
      },
      "name": {
        "type": "string",
        "pattern": "^[A-Za-z][A-Za-z0-9_]{0,31}$"
      },
      "frames": {
        "type": "array",
        "minItems": 1,
        "maxItems": 255,
        "items": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "shapeId",
            "ticks"
          ],
          "properties": {
            "shapeId": {
              "type": "string",
              "pattern": "^[A-Za-z0-9][A-Za-z0-9._:-]{0,63}$"
            },
            "ticks": {
              "type": "integer",
              "minimum": 1,
              "maximum": 255
            },
            "dx": {
              "type": "integer",
              "minimum": -512,
              "maximum": 511
            },
            "dy": {
              "type": "integer",
              "minimum": -512,
              "maximum": 511
            }
          }
        }
      }
    }
  },
  "project": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://clementina.dev/schema/project.schema.json",
    "title": "Clementina project manifest",
    "type": "object",
    "additionalProperties": false,
    "required": [
      "format",
      "version",
      "name",
      "target",
      "program",
      "assets"
    ],
    "properties": {
      "format": {
        "const": "clementina-project"
      },
      "version": {
        "const": 1
      },
      "name": {
        "type": "string",
        "minLength": 1,
        "maxLength": 80
      },
      "description": {
        "type": "string",
        "maxLength": 500
      },
      "target": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "machine"
        ],
        "properties": {
          "machine": {
            "const": "clementina-6502"
          },
          "phi2Hz": {
            "type": "integer",
            "minimum": 1,
            "maximum": 8000000
          }
        }
      },
      "program": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "kind",
          "entry"
        ],
        "properties": {
          "kind": {
            "enum": [
              "basic",
              "assembly",
              "mixed"
            ]
          },
          "entry": {
            "type": "string",
            "minLength": 1
          },
          "sources": {
            "type": "array",
            "uniqueItems": true,
            "items": {
              "type": "string",
              "minLength": 1
            }
          }
        }
      },
      "assets": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "palettes",
          "paletteConfigs",
          "tilesets",
          "shapes",
          "animations"
        ],
        "properties": {
          "palettes": {
            "type": "array",
            "uniqueItems": true,
            "items": {
              "type": "string",
              "minLength": 1
            }
          },
          "paletteConfigs": {
            "type": "array",
            "uniqueItems": true,
            "items": {
              "type": "string",
              "minLength": 1
            }
          },
          "tilesets": {
            "type": "array",
            "uniqueItems": true,
            "items": {
              "type": "string",
              "minLength": 1
            }
          },
          "shapes": {
            "type": "array",
            "uniqueItems": true,
            "items": {
              "type": "string",
              "minLength": 1
            }
          },
          "animations": {
            "type": "array",
            "uniqueItems": true,
            "items": {
              "type": "string",
              "minLength": 1
            }
          }
        }
      }
    }
  },
  "load-plan": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://clementina.dev/schema/load-plan.schema.json",
    "title": "Clementina runtime load plan",
    "type": "object",
    "additionalProperties": false,
    "required": [
      "format",
      "version",
      "steps"
    ],
    "properties": {
      "format": {
        "const": "clementina-load-plan"
      },
      "version": {
        "const": 1
      },
      "acknowledgedIssues": {
        "type": "array",
        "uniqueItems": true,
        "items": {
          "enum": [
            "audio-sequencer-sd-memory-overlap"
          ]
        }
      },
      "steps": {
        "type": "array",
        "minItems": 1,
        "maxItems": 6399,
        "items": {
          "oneOf": [
            {
              "type": "object",
              "additionalProperties": false,
              "required": [
                "kind",
                "path",
                "address",
                "length"
              ],
              "properties": {
                "kind": {
                  "const": "mia"
                },
                "path": {
                  "type": "string",
                  "minLength": 1,
                  "maxLength": 255
                },
                "address": {
                  "type": "integer",
                  "minimum": 0,
                  "maximum": 262143
                },
                "length": {
                  "type": "integer",
                  "minimum": 1,
                  "maximum": 262144
                }
              }
            },
            {
              "type": "object",
              "additionalProperties": false,
              "required": [
                "kind",
                "path",
                "loadAddress",
                "length"
              ],
              "properties": {
                "kind": {
                  "const": "prg"
                },
                "path": {
                  "type": "string",
                  "minLength": 1,
                  "maxLength": 255
                },
                "loadAddress": {
                  "type": "integer",
                  "minimum": 1,
                  "maximum": 49151
                },
                "length": {
                  "type": "integer",
                  "minimum": 1,
                  "maximum": 524288
                },
                "bank": {
                  "type": "integer",
                  "minimum": 1,
                  "maximum": 31
                },
                "runAddress": {
                  "type": "integer",
                  "minimum": 1,
                  "maximum": 65535
                }
              }
            }
          ]
        }
      }
    }
  }
} as const;
