// Generated by scripts/generate-schemas.mjs. Do not edit.
export const schemas = {
  "palette": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://clementina.dev/schema/palette.schema.json",
    "title": "Clementina palette",
    "type": "object",
    "additionalProperties": false,
    "required": [
      "format",
      "version",
      "id",
      "name",
      "colors"
    ],
    "properties": {
      "format": {
        "const": "clementina-palette"
      },
      "version": {
        "const": 1
      },
      "id": {
        "type": "string",
        "pattern": "^[A-Za-z0-9][A-Za-z0-9._:-]{0,63}$"
      },
      "name": {
        "type": "string",
        "minLength": 1,
        "maxLength": 64
      },
      "colors": {
        "type": "array",
        "minItems": 8,
        "maxItems": 8,
        "items": {
          "type": "integer",
          "minimum": 0,
          "maximum": 65535
        }
      }
    }
  },
  "palette-config": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://clementina.dev/schema/palette-config.schema.json",
    "title": "Clementina palette-bank configuration",
    "type": "object",
    "additionalProperties": false,
    "required": [
      "format",
      "version",
      "id",
      "name",
      "banks"
    ],
    "properties": {
      "format": {
        "const": "clementina-palette-config"
      },
      "version": {
        "const": 1
      },
      "id": {
        "type": "string",
        "pattern": "^[A-Za-z0-9][A-Za-z0-9._:-]{0,63}$"
      },
      "name": {
        "type": "string",
        "minLength": 1,
        "maxLength": 64
      },
      "banks": {
        "type": "array",
        "minItems": 16,
        "maxItems": 16,
        "items": {
          "anyOf": [
            {
              "type": "string",
              "pattern": "^[A-Za-z0-9][A-Za-z0-9._:-]{0,63}$"
            },
            {
              "type": "null"
            }
          ]
        }
      }
    }
  },
  "tileset": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://clementina.dev/schema/tileset.schema.json",
    "title": "Clementina tileset",
    "type": "object",
    "additionalProperties": false,
    "required": [
      "format",
      "version",
      "id",
      "name",
      "bpp",
      "chr",
      "authoring"
    ],
    "properties": {
      "format": {
        "const": "clementina-tileset"
      },
      "version": {
        "const": 1
      },
      "id": {
        "type": "string",
        "pattern": "^[A-Za-z0-9][A-Za-z0-9._:-]{0,63}$"
      },
      "name": {
        "type": "string",
        "pattern": "^[A-Za-z][A-Za-z0-9_-]{0,47}$"
      },
      "bpp": {
        "enum": [
          1,
          3
        ]
      },
      "chr": {
        "type": "array",
        "minItems": 6144,
        "maxItems": 6144,
        "items": {
          "type": "integer",
          "minimum": 0,
          "maximum": 255
        }
      },
      "authoring": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "tilePaletteBanks",
          "compositions"
        ],
        "properties": {
          "tilePaletteBanks": {
            "type": "array",
            "minItems": 256,
            "maxItems": 256,
            "items": {
              "type": "integer",
              "minimum": 0,
              "maximum": 15
            }
          },
          "compositions": {
            "type": "array",
            "items": {
              "type": "object",
              "additionalProperties": false,
              "required": [
                "name",
                "x",
                "y",
                "width",
                "height"
              ],
              "properties": {
                "name": {
                  "type": "string",
                  "minLength": 1,
                  "maxLength": 64
                },
                "x": {
                  "type": "integer",
                  "minimum": 0,
                  "maximum": 15
                },
                "y": {
                  "type": "integer",
                  "minimum": 0,
                  "maximum": 15
                },
                "width": {
                  "type": "integer",
                  "minimum": 1,
                  "maximum": 16
                },
                "height": {
                  "type": "integer",
                  "minimum": 1,
                  "maximum": 16
                }
              }
            }
          }
        }
      }
    }
  },
  "background": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://clementina.dev/schema/background.schema.json",
    "title": "Clementina background",
    "type": "object",
    "additionalProperties": false,
    "required": [
      "format",
      "version",
      "id",
      "name",
      "width",
      "height",
      "tilesetId",
      "altTilesetId",
      "cells"
    ],
    "properties": {
      "format": {
        "const": "clementina-background"
      },
      "version": {
        "const": 1
      },
      "id": {
        "type": "string",
        "pattern": "^[A-Za-z0-9][A-Za-z0-9._:-]{0,63}$"
      },
      "name": {
        "type": "string",
        "pattern": "^[A-Za-z][A-Za-z0-9_-]{0,47}$"
      },
      "width": {
        "type": "integer",
        "minimum": 1,
        "maximum": 1024
      },
      "height": {
        "type": "integer",
        "minimum": 1,
        "maximum": 1024
      },
      "tilesetId": {
        "type": "string",
        "pattern": "^[A-Za-z0-9][A-Za-z0-9._:-]{0,63}$"
      },
      "altTilesetId": {
        "type": "string",
        "pattern": "^[A-Za-z0-9][A-Za-z0-9._:-]{0,63}$"
      },
      "cells": {
        "type": "array",
        "minItems": 1,
        "maxItems": 200000,
        "items": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "tile",
            "paletteBank",
            "flipX",
            "flipY",
            "priority",
            "chrAlt"
          ],
          "properties": {
            "tile": {
              "type": "integer",
              "minimum": 0,
              "maximum": 255
            },
            "paletteBank": {
              "type": "integer",
              "minimum": 0,
              "maximum": 15
            },
            "flipX": {
              "type": "boolean"
            },
            "flipY": {
              "type": "boolean"
            },
            "priority": {
              "type": "boolean"
            },
            "chrAlt": {
              "type": "boolean"
            }
          }
        }
      }
    }
  },
  "overlay": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://clementina.dev/schema/overlay.schema.json",
    "title": "Clementina overlay",
    "type": "object",
    "additionalProperties": false,
    "required": [
      "format",
      "version",
      "id",
      "name",
      "tilesetId",
      "altTilesetId",
      "cells",
      "placeholders"
    ],
    "properties": {
      "format": {
        "const": "clementina-overlay"
      },
      "version": {
        "const": 1
      },
      "id": {
        "type": "string",
        "pattern": "^[A-Za-z0-9][A-Za-z0-9._:-]{0,63}$"
      },
      "name": {
        "type": "string",
        "pattern": "^[A-Za-z][A-Za-z0-9_-]{0,47}$"
      },
      "tilesetId": {
        "type": "string",
        "pattern": "^[A-Za-z0-9][A-Za-z0-9._:-]{0,63}$"
      },
      "altTilesetId": {
        "type": "string",
        "pattern": "^[A-Za-z0-9][A-Za-z0-9._:-]{0,63}$"
      },
      "cells": {
        "type": "array",
        "minItems": 1000,
        "maxItems": 1000,
        "items": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "tile",
            "paletteBank",
            "flipX",
            "flipY",
            "priority",
            "chrAlt"
          ],
          "properties": {
            "tile": {
              "type": "integer",
              "minimum": 0,
              "maximum": 255
            },
            "paletteBank": {
              "type": "integer",
              "minimum": 0,
              "maximum": 15
            },
            "flipX": {
              "type": "boolean"
            },
            "flipY": {
              "type": "boolean"
            },
            "priority": {
              "type": "boolean"
            },
            "chrAlt": {
              "type": "boolean"
            }
          }
        }
      },
      "placeholders": {
        "type": "array",
        "items": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "id",
            "name",
            "col",
            "row",
            "width",
            "height"
          ],
          "properties": {
            "id": {
              "type": "string",
              "pattern": "^[A-Za-z0-9][A-Za-z0-9._:-]{0,63}$"
            },
            "name": {
              "type": "string",
              "pattern": "^[A-Za-z][A-Za-z0-9_-]{0,47}$"
            },
            "col": {
              "type": "integer",
              "minimum": 0,
              "maximum": 39
            },
            "row": {
              "type": "integer",
              "minimum": 0,
              "maximum": 24
            },
            "width": {
              "type": "integer",
              "minimum": 1,
              "maximum": 40
            },
            "height": {
              "type": "integer",
              "minimum": 1,
              "maximum": 25
            }
          }
        }
      }
    }
  },
  "shape": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://clementina.dev/schema/shape.schema.json",
    "title": "Clementina shape",
    "type": "object",
    "additionalProperties": false,
    "required": [
      "format",
      "version",
      "id",
      "name",
      "tilesetId",
      "sprites"
    ],
    "properties": {
      "format": {
        "const": "clementina-shape"
      },
      "version": {
        "const": 1
      },
      "id": {
        "type": "string",
        "pattern": "^[A-Za-z0-9][A-Za-z0-9._:-]{0,63}$"
      },
      "name": {
        "type": "string",
        "pattern": "^[A-Za-z][A-Za-z0-9_]{0,31}$"
      },
      "tilesetId": {
        "type": "string",
        "pattern": "^[A-Za-z0-9][A-Za-z0-9._:-]{0,63}$"
      },
      "canvasPixelWidth": {
        "type": "integer",
        "minimum": 1,
        "maximum": 320
      },
      "canvasPixelHeight": {
        "type": "integer",
        "minimum": 1,
        "maximum": 200
      },
      "originAnchor": {
        "enum": [
          "top-left",
          "center",
          "bottom-center",
          "custom"
        ]
      },
      "originX": {
        "type": "integer",
        "minimum": -32768,
        "maximum": 32767
      },
      "originY": {
        "type": "integer",
        "minimum": -32768,
        "maximum": 32767
      },
      "sprites": {
        "type": "array",
        "maxItems": 64,
        "items": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "tile",
            "x",
            "y",
            "paletteBank",
            "flipX",
            "flipY"
          ],
          "properties": {
            "tile": {
              "type": "integer",
              "minimum": 0,
              "maximum": 255
            },
            "x": {
              "type": "integer",
              "minimum": -512,
              "maximum": 511
            },
            "y": {
              "type": "integer",
              "minimum": -256,
              "maximum": 255
            },
            "paletteBank": {
              "type": "integer",
              "minimum": 0,
              "maximum": 15
            },
            "flipX": {
              "type": "boolean"
            },
            "flipY": {
              "type": "boolean"
            }
          }
        }
      }
    }
  },
  "animation": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://clementina.dev/schema/animation.schema.json",
    "title": "Clementina animation",
    "type": "object",
    "additionalProperties": false,
    "required": [
      "format",
      "version",
      "id",
      "name",
      "frames"
    ],
    "properties": {
      "format": {
        "const": "clementina-animation"
      },
      "version": {
        "const": 1
      },
      "id": {
        "type": "string",
        "pattern": "^[A-Za-z0-9][A-Za-z0-9._:-]{0,63}$"
      },
      "name": {
        "type": "string",
        "pattern": "^[A-Za-z][A-Za-z0-9_]{0,31}$"
      },
      "frames": {
        "type": "array",
        "minItems": 1,
        "maxItems": 255,
        "items": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "shapeId",
            "ticks"
          ],
          "properties": {
            "shapeId": {
              "type": "string",
              "pattern": "^[A-Za-z0-9][A-Za-z0-9._:-]{0,63}$"
            },
            "ticks": {
              "type": "integer",
              "minimum": 1,
              "maximum": 255
            },
            "dx": {
              "type": "integer",
              "minimum": -512,
              "maximum": 511
            },
            "dy": {
              "type": "integer",
              "minimum": -512,
              "maximum": 511
            },
            "flipX": {
              "type": "boolean"
            },
            "flipY": {
              "type": "boolean"
            }
          }
        }
      }
    }
  },
  "instrument": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://clementina.dev/schema/instrument.schema.json",
    "title": "Clementina instrument",
    "type": "object",
    "additionalProperties": false,
    "required": [
      "format",
      "version",
      "id",
      "name",
      "wave",
      "pulse",
      "attack",
      "decay",
      "sustain",
      "release",
      "volume"
    ],
    "properties": {
      "format": {
        "const": "clementina-instrument"
      },
      "version": {
        "const": 1
      },
      "id": {
        "type": "string",
        "pattern": "^[A-Za-z0-9][A-Za-z0-9._:-]{0,63}$"
      },
      "name": {
        "type": "string",
        "pattern": "^[A-Za-z][A-Za-z0-9_]{0,31}$"
      },
      "wave": {
        "type": "integer",
        "minimum": 0,
        "maximum": 4
      },
      "pulse": {
        "type": "integer",
        "minimum": 0,
        "maximum": 255
      },
      "attack": {
        "type": "integer",
        "minimum": 0,
        "maximum": 15
      },
      "decay": {
        "type": "integer",
        "minimum": 0,
        "maximum": 15
      },
      "sustain": {
        "type": "integer",
        "minimum": 0,
        "maximum": 15
      },
      "release": {
        "type": "integer",
        "minimum": 0,
        "maximum": 15
      },
      "volume": {
        "type": "integer",
        "minimum": 0,
        "maximum": 255
      }
    }
  },
  "sound": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://clementina.dev/schema/sound.schema.json",
    "title": "Clementina sound effect",
    "type": "object",
    "additionalProperties": false,
    "required": [
      "format",
      "version",
      "id",
      "name",
      "attack",
      "decay",
      "sustain",
      "release",
      "pan",
      "frames"
    ],
    "properties": {
      "format": {
        "const": "clementina-sound"
      },
      "version": {
        "const": 1
      },
      "id": {
        "type": "string",
        "pattern": "^[A-Za-z0-9][A-Za-z0-9._:-]{0,63}$"
      },
      "name": {
        "type": "string",
        "pattern": "^[A-Za-z][A-Za-z0-9_]{0,31}$"
      },
      "attack": {
        "type": "integer",
        "minimum": 0,
        "maximum": 15
      },
      "decay": {
        "type": "integer",
        "minimum": 0,
        "maximum": 15
      },
      "sustain": {
        "type": "integer",
        "minimum": 0,
        "maximum": 15
      },
      "release": {
        "type": "integer",
        "minimum": 0,
        "maximum": 15
      },
      "pan": {
        "type": "integer",
        "minimum": -64,
        "maximum": 63
      },
      "frames": {
        "type": "array",
        "minItems": 1,
        "maxItems": 600,
        "items": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "freq",
            "volume",
            "pulse",
            "wave",
            "gate"
          ],
          "properties": {
            "freq": {
              "type": "integer",
              "minimum": 0,
              "maximum": 65535
            },
            "volume": {
              "type": "integer",
              "minimum": 0,
              "maximum": 255
            },
            "pulse": {
              "type": "integer",
              "minimum": 0,
              "maximum": 255
            },
            "wave": {
              "type": "integer",
              "minimum": 0,
              "maximum": 4
            },
            "gate": {
              "type": "boolean"
            }
          }
        }
      }
    }
  },
  "song": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://clementina.dev/schema/song.schema.json",
    "title": "Clementina song",
    "type": "object",
    "additionalProperties": false,
    "required": [
      "format",
      "version",
      "id",
      "name",
      "bpm",
      "stepsPerBeat",
      "beatsPerBar",
      "length",
      "voices"
    ],
    "properties": {
      "format": {
        "const": "clementina-song"
      },
      "version": {
        "const": 1
      },
      "id": {
        "type": "string",
        "pattern": "^[A-Za-z0-9][A-Za-z0-9._:-]{0,63}$"
      },
      "name": {
        "type": "string",
        "pattern": "^[A-Za-z][A-Za-z0-9_]{0,31}$"
      },
      "bpm": {
        "type": "integer",
        "minimum": 20,
        "maximum": 400
      },
      "stepsPerBeat": {
        "enum": [
          1,
          2,
          3,
          4,
          6,
          8
        ]
      },
      "beatsPerBar": {
        "type": "integer",
        "minimum": 1,
        "maximum": 16
      },
      "length": {
        "type": "integer",
        "minimum": 1,
        "maximum": 4096
      },
      "loopStart": {
        "type": "integer",
        "minimum": 0,
        "maximum": 4095
      },
      "voices": {
        "type": "array",
        "minItems": 4,
        "maxItems": 4,
        "items": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "pan",
            "notes"
          ],
          "properties": {
            "pan": {
              "type": "integer",
              "minimum": -64,
              "maximum": 63
            },
            "notes": {
              "type": "array",
              "maxItems": 4096,
              "items": {
                "type": "object",
                "additionalProperties": false,
                "required": [
                  "step",
                  "length",
                  "pitch",
                  "instrumentId"
                ],
                "properties": {
                  "step": {
                    "type": "integer",
                    "minimum": 0,
                    "maximum": 4095
                  },
                  "length": {
                    "type": "integer",
                    "minimum": 1,
                    "maximum": 4096
                  },
                  "pitch": {
                    "type": "integer",
                    "minimum": 0,
                    "maximum": 95
                  },
                  "instrumentId": {
                    "type": "string",
                    "pattern": "^[A-Za-z0-9][A-Za-z0-9._:-]{0,63}$"
                  },
                  "legato": {
                    "type": "boolean"
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "project": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://clementina.dev/schema/project.schema.json",
    "title": "Clementina project manifest",
    "type": "object",
    "additionalProperties": false,
    "required": [
      "format",
      "version",
      "name",
      "target",
      "program",
      "assets"
    ],
    "properties": {
      "format": {
        "const": "clementina-project"
      },
      "version": {
        "const": 1
      },
      "name": {
        "type": "string",
        "minLength": 1,
        "maxLength": 80
      },
      "description": {
        "type": "string",
        "maxLength": 500
      },
      "target": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "machine"
        ],
        "properties": {
          "machine": {
            "const": "clementina-6502"
          },
          "phi2Hz": {
            "type": "integer",
            "minimum": 1,
            "maximum": 8000000
          }
        }
      },
      "program": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "kind",
          "entry"
        ],
        "properties": {
          "kind": {
            "enum": [
              "basic",
              "assembly",
              "mixed"
            ]
          },
          "entry": {
            "type": "string",
            "minLength": 1
          },
          "sources": {
            "type": "array",
            "uniqueItems": true,
            "items": {
              "type": "string",
              "minLength": 1
            }
          }
        }
      },
      "assets": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "palettes",
          "paletteConfigs",
          "tilesets",
          "backgrounds",
          "overlays",
          "shapes",
          "animations"
        ],
        "properties": {
          "palettes": {
            "type": "array",
            "uniqueItems": true,
            "items": {
              "type": "string",
              "minLength": 1
            }
          },
          "paletteConfigs": {
            "type": "array",
            "uniqueItems": true,
            "items": {
              "type": "string",
              "minLength": 1
            }
          },
          "tilesets": {
            "type": "array",
            "uniqueItems": true,
            "items": {
              "type": "string",
              "minLength": 1
            }
          },
          "backgrounds": {
            "type": "array",
            "uniqueItems": true,
            "items": {
              "type": "string",
              "minLength": 1
            }
          },
          "overlays": {
            "type": "array",
            "uniqueItems": true,
            "items": {
              "type": "string",
              "minLength": 1
            }
          },
          "shapes": {
            "type": "array",
            "uniqueItems": true,
            "items": {
              "type": "string",
              "minLength": 1
            }
          },
          "animations": {
            "type": "array",
            "uniqueItems": true,
            "items": {
              "type": "string",
              "minLength": 1
            }
          },
          "instruments": {
            "type": "array",
            "uniqueItems": true,
            "items": {
              "type": "string",
              "minLength": 1
            }
          },
          "sounds": {
            "type": "array",
            "uniqueItems": true,
            "items": {
              "type": "string",
              "minLength": 1
            }
          },
          "songs": {
            "type": "array",
            "uniqueItems": true,
            "items": {
              "type": "string",
              "minLength": 1
            }
          }
        }
      },
      "build": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "outputDirectory"
        ],
        "anyOf": [
          {
            "properties": {
              "assembly": {
                "type": "object"
              }
            },
            "required": [
              "assembly"
            ]
          },
          {
            "properties": {
              "basic": {
                "type": "object"
              }
            },
            "required": [
              "basic"
            ]
          }
        ],
        "properties": {
          "outputDirectory": {
            "type": "string",
            "minLength": 1
          },
          "assembly": {
            "type": "object",
            "additionalProperties": false,
            "required": [
              "linkerConfig",
              "outputName",
              "loadAddress",
              "entrySymbol"
            ],
            "properties": {
              "linkerConfig": {
                "type": "string",
                "minLength": 1
              },
              "outputName": {
                "type": "string",
                "pattern": "^[A-Za-z][A-Za-z0-9_-]{0,47}$"
              },
              "loadAddress": {
                "type": "integer",
                "minimum": 1,
                "maximum": 49151
              },
              "bank": {
                "type": "integer",
                "minimum": 1,
                "maximum": 31
              },
              "entrySymbol": {
                "type": "string",
                "pattern": "^[A-Za-z_@][A-Za-z0-9_@.$]*$"
              },
              "includeDirectories": {
                "type": "array",
                "uniqueItems": true,
                "items": {
                  "type": "string",
                  "minLength": 1
                }
              },
              "defines": {
                "type": "object",
                "propertyNames": {
                  "pattern": "^[A-Za-z_][A-Za-z0-9_]*$"
                },
                "additionalProperties": {
                  "anyOf": [
                    {
                      "type": "string",
                      "pattern": "^[A-Za-z0-9_.$+-]+$"
                    },
                    {
                      "type": "integer"
                    }
                  ]
                }
              }
            }
          },
          "basic": {
            "type": "object",
            "additionalProperties": false,
            "required": [
              "outputName"
            ],
            "properties": {
              "outputName": {
                "type": "string",
                "pattern": "^[A-Za-z][A-Za-z0-9_-]{0,47}$"
              }
            }
          },
          "assets": {
            "type": "object",
            "additionalProperties": false,
            "required": [
              "slots",
              "include"
            ],
            "properties": {
              "folder": {
                "type": "string",
                "pattern": "^[A-Za-z0-9_-]{1,32}(/[A-Za-z0-9_-]{1,32}){0,3}$"
              },
              "checks": {
                "type": "boolean"
              },
              "slots": {
                "type": "array",
                "maxItems": 64,
                "items": {
                  "type": "object",
                  "additionalProperties": false,
                  "required": [
                    "name",
                    "size"
                  ],
                  "properties": {
                    "name": {
                      "type": "string",
                      "pattern": "^[A-Za-z][A-Za-z0-9_]{0,31}$"
                    },
                    "mia": {
                      "type": "integer",
                      "minimum": 0,
                      "maximum": 262143
                    },
                    "bank": {
                      "type": "integer",
                      "minimum": 1,
                      "maximum": 31
                    },
                    "address": {
                      "type": "integer",
                      "minimum": 32768,
                      "maximum": 49151
                    },
                    "size": {
                      "type": "integer",
                      "minimum": 1,
                      "maximum": 507904
                    }
                  }
                }
              },
              "include": {
                "type": "array",
                "maxItems": 1024,
                "items": {
                  "type": "object",
                  "additionalProperties": false,
                  "required": [
                    "kind",
                    "id",
                    "slot"
                  ],
                  "properties": {
                    "kind": {
                      "enum": [
                        "paletteConfig",
                        "tileset",
                        "background",
                        "overlay",
                        "sprites",
                        "song",
                        "sound"
                      ]
                    },
                    "id": {
                      "type": "string",
                      "pattern": "^[A-Za-z0-9][A-Za-z0-9._:-]{0,63}$"
                    },
                    "slot": {
                      "type": "string",
                      "pattern": "^[A-Za-z][A-Za-z0-9_]{0,31}$"
                    },
                    "file": {
                      "type": "string",
                      "pattern": "^[A-Za-z0-9_-]{1,32}(\\.[A-Za-z0-9_-]{1,8})?$"
                    }
                  }
                }
              }
            }
          },
          "video": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
              "paletteConfigId": {
                "type": "string",
                "pattern": "^[A-Za-z0-9][A-Za-z0-9._:-]{0,63}$"
              },
              "tilesets": {
                "type": "array",
                "maxItems": 8,
                "items": {
                  "type": "object",
                  "additionalProperties": false,
                  "required": [
                    "tilesetId",
                    "bank"
                  ],
                  "properties": {
                    "tilesetId": {
                      "type": "string",
                      "pattern": "^[A-Za-z0-9][A-Za-z0-9._:-]{0,63}$"
                    },
                    "bank": {
                      "type": "integer",
                      "minimum": 0,
                      "maximum": 7
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "load-plan": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://clementina.dev/schema/load-plan.schema.json",
    "title": "Clementina runtime load plan",
    "type": "object",
    "additionalProperties": false,
    "required": [
      "format",
      "version",
      "steps"
    ],
    "properties": {
      "format": {
        "const": "clementina-load-plan"
      },
      "version": {
        "const": 1
      },
      "steps": {
        "type": "array",
        "minItems": 1,
        "maxItems": 6399,
        "items": {
          "oneOf": [
            {
              "type": "object",
              "additionalProperties": false,
              "required": [
                "kind",
                "path",
                "address",
                "length"
              ],
              "properties": {
                "kind": {
                  "const": "mia"
                },
                "path": {
                  "type": "string",
                  "minLength": 1,
                  "maxLength": 255
                },
                "address": {
                  "type": "integer",
                  "minimum": 0,
                  "maximum": 262143
                },
                "length": {
                  "type": "integer",
                  "minimum": 1,
                  "maximum": 262144
                }
              }
            },
            {
              "type": "object",
              "additionalProperties": false,
              "required": [
                "kind",
                "path",
                "loadAddress",
                "length"
              ],
              "properties": {
                "kind": {
                  "const": "prg"
                },
                "path": {
                  "type": "string",
                  "minLength": 1,
                  "maxLength": 255
                },
                "loadAddress": {
                  "type": "integer",
                  "minimum": 1,
                  "maximum": 49151
                },
                "length": {
                  "type": "integer",
                  "minimum": 1,
                  "maximum": 524288
                },
                "bank": {
                  "type": "integer",
                  "minimum": 1,
                  "maximum": 31
                },
                "runAddress": {
                  "type": "integer",
                  "minimum": 1,
                  "maximum": 65535
                }
              }
            },
            {
              "type": "object",
              "additionalProperties": false,
              "required": [
                "kind",
                "path",
                "length"
              ],
              "properties": {
                "kind": {
                  "const": "basic"
                },
                "path": {
                  "type": "string",
                  "minLength": 1,
                  "maxLength": 255
                },
                "length": {
                  "type": "integer",
                  "minimum": 2,
                  "maximum": 65535
                }
              }
            }
          ]
        }
      }
    }
  }
} as const;
