import {readFile, writeFile} from 'node:fs/promises';
const names = ['palette', 'palette-config', 'tileset', 'shape', 'animation', 'project'];
const schemas = {};
for (const name of names) schemas[name] = JSON.parse(await readFile(new URL(`../specs/schema/${name}.schema.json`, import.meta.url), 'utf8'));
const output = '// Generated by scripts/generate-schemas.mjs. Do not edit.\nexport const schemas = ' + JSON.stringify(schemas, null, 2) + ' as const;\n';
const target = new URL('../packages/core/src/schemas.ts', import.meta.url);
if (process.argv.includes('--check')) {
  if (await readFile(target, 'utf8') !== output) throw Error('Generated schemas are stale');
} else await writeFile(target, output);
